# -*- coding: utf-8 -*-
"""ComercioListo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cBDadDVsoYTS21hNZY14TJ-6ayQQIQb
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import nltk

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import tensorflow as tf

df = pd.read_csv("comercio-opiniones.csv")

df.head()

df.info()

df.isnull().sum()

df.describe()

df["reviews.doRecommend"].value_counts()

df["reviews.rating"].value_counts()

plt.figure(figsize=(6,4))

sns.countplot(x="reviews.doRecommend", data=df)

plt.title("Clientes que recomiendan el producto")

plt.show()

df["reviews.rating"].value_counts().sort_index()

plt.figure(figsize=(6,4))

sns.countplot(x="reviews.rating", data=df)

plt.title("Distribución de puntuaciones")

plt.xlabel("Estrellas")

plt.show()

df["sentimiento"] = df["reviews.rating"].apply(
    lambda x: 1 if x >= 4 else 0
)

df["sentimiento"].value_counts()

sns.countplot(
    x="sentimiento",
    data=df
)

plt.title("Distribución de sentimientos")
plt.show()

df["longitud_texto"] = df["reviews.text"].astype(str).apply(len)

plt.figure(figsize=(8,4))

sns.histplot(
    df["longitud_texto"],
    bins=30
)

plt.title("Longitud de las reseñas")
plt.show()

df["texto_completo"] = (
    df["reviews.title"].fillna("")
    + " " +
    df["reviews.text"].fillna("")
)

df = df.dropna(subset=["texto_completo"])

import re
import string

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("omw-1.4")

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def limpiar_texto(texto):
    texto = texto.lower()

    # Eliminar URLs
    texto = re.sub(r"http\S+|www\S+", "", texto)

    # Eliminar puntuación
    texto = texto.translate(str.maketrans("", "", string.punctuation))

    # Tokenizar
    palabras = word_tokenize(texto)

    # Eliminar stopwords y lematizar
    palabras = [
        lemmatizer.lemmatize(palabra)
        for palabra in palabras
        if palabra not in stop_words
    ]

    return " ".join(palabras)

df["texto_limpio"] = df["texto_completo"].apply(limpiar_texto)

df = df[df["texto_limpio"].str.len() > 0].reset_index(drop=True)

df["sentimiento"] = df["sentimiento"].astype(int)

df.shape

from collections import Counter

def top_palabras(textos, n=15):
    todas = " ".join(textos).split()
    return Counter(todas).most_common(n)

top_pos = top_palabras(df[df["sentimiento"] == 1]["texto_limpio"])
top_neg = top_palabras(df[df["sentimiento"] == 0]["texto_limpio"])

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.barplot(x=[c for _, c in top_pos], y=[p for p, _ in top_pos], ax=axes[0], color="seagreen")
axes[0].set_title("Palabras más frecuentes - Reseñas positivas")

sns.barplot(x=[c for _, c in top_neg], y=[p for p, _ in top_neg], ax=axes[1], color="indianred")
axes[1].set_title("Palabras más frecuentes - Reseñas negativas")

plt.tight_layout()
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer

X = df["texto_limpio"]
y = df["sentimiento"]

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train_text.shape[0], " Test:", X_test_text.shape[0])
print("Proporción de clases en train:")
print(y_train.value_counts(normalize=True))

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))

X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

X_train_tfidf.shape, X_test_tfidf.shape

from sklearn.linear_model import LogisticRegression

modelo_lr = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)
modelo_lr.fit(X_train_tfidf, y_train)

y_pred_lr = modelo_lr.predict(X_test_tfidf)

acc_lr = accuracy_score(y_test, y_pred_lr)
print("Accuracy Regresión Logística:", round(acc_lr, 4))
print(classification_report(y_test, y_pred_lr, target_names=["Negativa", "Positiva"]))

cm_lr = confusion_matrix(y_test, y_pred_lr)

plt.figure(figsize=(5, 4))
sns.heatmap(cm_lr, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Negativa", "Positiva"], yticklabels=["Negativa", "Positiva"])
plt.title("Matriz de confusión - Regresión Logística")
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.show()

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

VOCAB_SIZE = 10000
MAX_LEN = 100

tokenizer_keras = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer_keras.fit_on_texts(X_train_text)

X_train_seq = tokenizer_keras.texts_to_sequences(X_train_text)
X_test_seq = tokenizer_keras.texts_to_sequences(X_test_text)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding="post", truncating="post")
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding="post", truncating="post")

X_train_pad.shape, X_test_pad.shape

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout

modelo_dl = Sequential([
    Embedding(input_dim=VOCAB_SIZE, output_dim=32, input_length=MAX_LEN),
    GlobalAveragePooling1D(),
    Dense(16, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

modelo_dl.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
modelo_dl.summary()

from sklearn.utils.class_weight import compute_class_weight

pesos = compute_class_weight(class_weight="balanced", classes=np.unique(y_train), y=y_train)
pesos_dict = {0: pesos[0], 1: pesos[1]}
pesos_dict

historia = modelo_dl.fit(
    X_train_pad, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    class_weight=pesos_dict,
    verbose=1
)

y_pred_dl_proba = modelo_dl.predict(X_test_pad)
y_pred_dl = (y_pred_dl_proba > 0.5).astype(int).ravel()

acc_dl = accuracy_score(y_test, y_pred_dl)
print("Accuracy Red Neuronal (Deep Learning):", round(acc_dl, 4))
print(classification_report(y_test, y_pred_dl, target_names=["Negativa", "Positiva"]))

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(historia.history["accuracy"], label="Train")
axes[0].plot(historia.history["val_accuracy"], label="Validación")
axes[0].set_title("Accuracy por época")
axes[0].set_xlabel("Época")
axes[0].legend()

axes[1].plot(historia.history["loss"], label="Train")
axes[1].plot(historia.history["val_loss"], label="Validación")
axes[1].set_title("Loss por época")
axes[1].set_xlabel("Época")
axes[1].legend()

plt.tight_layout()
plt.show()

cm_dl = confusion_matrix(y_test, y_pred_dl)

plt.figure(figsize=(5, 4))
sns.heatmap(cm_dl, annot=True, fmt="d", cmap="Purples",
            xticklabels=["Negativa", "Positiva"], yticklabels=["Negativa", "Positiva"])
plt.title("Matriz de confusión - Red Neuronal (Deep Learning)")
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.show()

from sklearn.metrics import f1_score

f1_lr = f1_score(y_test, y_pred_lr, average="macro")
f1_dl = f1_score(y_test, y_pred_dl, average="macro")

comparacion = pd.DataFrame({
    "Modelo": ["Regresión Logística (TF-IDF)", "Red Neuronal (Embedding - Keras)"],
    "Accuracy": [acc_lr, acc_dl],
    "F1-score (macro)": [f1_lr, f1_dl]
})
comparacion

comparacion_melt = comparacion.melt(id_vars="Modelo", var_name="Métrica", value_name="Valor")

plt.figure(figsize=(8, 5))
sns.barplot(data=comparacion_melt, x="Métrica", y="Valor", hue="Modelo")
plt.title("Comparación de desempeño entre modelos")
plt.ylim(0, 1)
plt.legend(loc="lower right")
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.barplot(x=[c for _, c in top_pos], y=[p for p, _ in top_pos], ax=axes[0], color="seagreen")
axes[0].set_title("Palabras más frecuentes - Reseñas positivas")

sns.barplot(x=[c for _, c in top_neg], y=[p for p, _ in top_neg], ax=axes[1], color="indianred")
axes[1].set_title("Palabras más frecuentes - Reseñas negativas")

plt.tight_layout()
plt.show()

